### ISSUE TITLE
requirements.txt?

### ISSUE THREAD

**Issue by kot83** [ClarityMoe/kitsuchan#7]
~~Better than reading through the README.md~~

**Comment by sr229** [comment]
CC @n303p4

**Comment by n303p4** [comment]
I should mentioned that k3 by design only depends on Python 3.6 as a minimum - everything else is optional. The modules, the aiohttp ClientSession, and the Discord bot do require additional dependencies, but they aren't required for the k3 core to function. So what I'm probably going to do is name the file `optional-requirements.txt`.

**Comment by n303p4** [comment]
No `requirements.txt`, but there is now a `setup.py` that specifies optional dependencies.

**Comment by n303p4** [comment]
No `requirements.txt`, but there is now a `setup.py` that specifies optional dependencies.
